### ISSUE TITLE
Lock DB file

### ISSUE THREAD

**Issue by flipmcf** [flipmcf/CasterPak#12]
It's possible for cleanup and an HTTP request to happen simultaneously.  Or multiple HTTP requests to modify the cache db simultaneously.

We need a way to lock the tinyDB instance and prevent synchronous access.  It's not thread safe.

Example:
```
[2022-06-28 17:05:01,062] ERROR in app: Exception on /i/20190315/1475/1_0yr7lkwq_1_,lcrv4ssw,h8eu9lpn,bzzbs232,xf8strxb,_1.mp4.csmil/manifest.m3u8 [GET]
Traceback (most recent call last):
  File "/home/mcfaddenm/repos/CasterPak/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mcfaddenm/repos/CasterPak/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mcfaddenm/repos/CasterPak/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mcfaddenm/repos/CasterPak/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mcfaddenm/repos/CasterPak/casterpak.py", line 133, in parent_manifest
    vodhls_manager.manage_input_file()
  File "/home/mcfaddenm/repos/CasterPak/vodhls/base.py", line 66, in manage_input_file
    self.db.addrecord(filename=self.filename, timestamp=None)
  File "/home/mcfaddenm/repos/CasterPak/cachedb.py", line 26, in addrecord
    self.db.upsert({'f': filename, 't': int(timestamp.timestamp())},
  File "/home/mcfaddenm/repos/CasterPak/venv/lib/python3.8/site-packages/tinydb/table.py", line 518, in upsert
    updated_docs: Optional[List[int]] = self.update(document, cond, doc_ids)
  File "/home/mcfaddenm/repos/CasterPak/venv/lib/python3.8/site-packages/tinydb/table.py", line 415, in update
    self._update_table(updater)
  File "/home/mcfaddenm/repos/CasterPak/venv/lib/python3.8/site-packages/tinydb/table.py", line 714, in _update_table
    tables = self._storage.read()
  File "/home/mcfaddenm/repos/CasterPak/venv/lib/python3.8/site-packages/tinydb/storages.py", line 125, in read
    return json.load(self._handle)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 254 (char 253)

```

**Comment by flipmcf** [comment]
There are some threading issues.   I totally broke it with:
 1) set segment_file_age = 0 so cleanup always happens.


 2) launch gnuicorn, 4 threads:
    ` ./venv/bin/python3 -m gunicorn -b :5000 --config gunicorn-
 debug.conf.py`

 3) pound on a segment manifest
    ` watch -n 0.2 curl -i
 http://localhost:5000/i/20220705/1251/1_p0kdyds9_1_d3poh4s7_1.mp4/index_0_av.m3u8`


 4) in another terminal, pound on cleanup:
     ` watch -n 0.5 ./venv/bin/python3 cleanup.py `

 Lots of TinyDB database problems with the json file.  eventually the file
 becomes totally unreadable and the whole system just won't work.

 I tried adding some simple multiprocessing locking to it, but the answer
 is to drop tinyDB and use SQLite as the cache database.

**Comment by flipmcf** [comment]
As of 2c6c810 this seems to be ok.
